-- 20260907_tsl_certificates.sql
-- TSL (Trust Service List) certificate storage for Russian accredited CAs

CREATE TABLE IF NOT EXISTS public.tsl_certificates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thumbprint text NOT NULL UNIQUE,
  subject_dn text NOT NULL,
  issuer_dn text NOT NULL,
  not_before timestamptz NOT NULL,
  not_after timestamptz NOT NULL,
  certificate_der text NOT NULL,
  is_root boolean NOT NULL DEFAULT false,
  authority_name text NOT NULL,
  authority_inn text,
  authority_ogrn text,
  tsl_version integer NOT NULL,
  tsl_date timestamptz NOT NULL,
  last_synced_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tsl_certificates_thumbprint_idx ON public.tsl_certificates (thumbprint);
CREATE INDEX IF NOT EXISTS tsl_certificates_subject_idx ON public.tsl_certificates (subject_dn);
CREATE INDEX IF NOT EXISTS tsl_certificates_authority_idx ON public.tsl_certificates (authority_name);
CREATE INDEX IF NOT EXISTS tsl_certificates_is_root_idx ON public.tsl_certificates (is_root) WHERE is_root = true;
CREATE INDEX IF NOT EXISTS tsl_certificates_not_after_idx ON public.tsl_certificates (not_after);
CREATE INDEX IF NOT EXISTS tsl_certificates_tsl_version_idx ON public.tsl_certificates (tsl_version DESC);

COMMENT ON TABLE public.tsl_certificates IS 'Certificates from Russian Trust Service List (Минцифры)';
COMMENT ON COLUMN public.tsl_certificates.thumbprint IS 'SHA-1 thumbprint of certificate';
COMMENT ON COLUMN public.tsl_certificates.subject_dn IS 'Distinguished Name of subject';
COMMENT ON COLUMN public.tsl_certificates.issuer_dn IS 'Distinguished Name of issuer';
COMMENT ON COLUMN public.tsl_certificates.certificate_der IS 'Base64-encoded DER (X.509)';
COMMENT ON COLUMN public.tsl_certificates.is_root IS 'True if subject == issuer (self-signed root)';
COMMENT ON COLUMN public.tsl_certificates.tsl_version IS 'Version of TSL when this cert was synced';
COMMENT ON COLUMN public.tsl_certificates.tsl_date IS 'Date when TSL was generated by Минцифры';

ALTER TABLE public.tsl_certificates ENABLE ROW LEVEL SECURITY;

-- Service role has full access (for cron sync)
CREATE POLICY tsl_certificates_service_all ON public.tsl_certificates
  FOR ALL
  USING (auth.jwt() ->> 'role' = 'service_role')
  WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

-- All authenticated users can read (it's public trust info)
CREATE POLICY tsl_certificates_authenticated_read ON public.tsl_certificates
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Metadata for last sync
CREATE TABLE IF NOT EXISTS public.tsl_sync_metadata (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  last_sync_at timestamptz,
  last_version integer,
  last_date timestamptz,
  total_certificates integer DEFAULT 0,
  root_certificates integer DEFAULT 0,
  last_error text,
  last_error_at timestamptz,
  CONSTRAINT only_one_row CHECK (id = 1)
);

COMMENT ON TABLE public.tsl_sync_metadata IS 'Metadata for the last TSL sync operation';

INSERT INTO public.tsl_sync_metadata (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.tsl_sync_metadata ENABLE ROW LEVEL SECURITY;

CREATE POLICY tsl_sync_metadata_service_all ON public.tsl_sync_metadata
  FOR ALL
  USING (auth.jwt() ->> 'role' = 'service_role')
  WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY tsl_sync_metadata_read ON public.tsl_sync_metadata
  FOR SELECT
  USING (true);