name: Deploy GHCR image to CapRover (staging)

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Полное имя образа'
        required: true
        default: 'ghcr.io/dogovor-expert/dogovor-expert-app:staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CapRover deploy via App Token
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_APP_NAME }}'
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: '${{ github.event.inputs.image }}'
